#!/usr/bin/env bash
#This code is from feedback I recieved.

# http://www.reddit.com/r/bash/comments/21moty/this_is_my_first_to_order_bash_script_can_i_get/
traverse() {
  local file dir=$1 indent=$2
  cd "$dir" || return
  for file in .* *; do
    # skip current/previous dirs and unresolved wildcards
    case "$file" in
    "." | ".." | ".*" | "*" ) continue ;;
    esac
    echo "$indent$file"
    # recursively traverse/indent directories that are not symlinks
    if [[ -d "$file" && ! -L "$file" ]]; then
      traverse "$dir/$file" "$indent    "
    fi
  done
  cd ..
}

traverse ${1:-$HOME} > ${2:-$HOME/hdl.txt}